#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= board_ijb_vzw.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_bt.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_camera.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_input.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_misc.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_panel.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= platform_ijb_vzw_snd.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= gpiomux_ijb_vzw.o
obj-$(CONFIG_MACH_LGE_IJB_BOARD_VZW)	+= devices_ijb_vzw.o
